# Dummy file for using query_database.py functions

## Query functions

In [2]:
import scripts.query_database as function
import pandas as pd

In [2]:
# get all reviews
reviews_db = function.get_reviews()
reviews_db.head(5)

         _id  tmdb_id                                             review
0  tt0004972      618  [{'author': 'prabhushakti', 'rating': 10.0, 'u...
1  tt0008431   285807  [{'author': 'Le_Schpountz', 'rating': 6.0, 'ur...
2  tt0009062    48214  [{'author': 'germish', 'rating': 9.5, 'url': '...
3  tt0009143   463115  [{'author': '27B/6', 'rating': None, 'url': 'h...
4  tt0010058   352098  [{'author': 'ObscurHollywood', 'rating': None,...

In [3]:
# get all movies, no constrains 
combined_db = function.get_combined()
combined_db.head(5)

,_id,primaryTitle,originalTitle,isAdult,release_year,runtimeMinutes,genres,imdb_avgRating,imdb_numVotes,Directors,...,top_10_cast_popularity,num_of_crew,top_10_crew_popularity_mean,crews,top_10_crew_popularity,tmdb_avgRating,tmdb_numVotes,Writers,homepage,belongs_to_collection
0,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,0,1906.0,70.0,"[Action, Adventure, Biography, History, Drama,...",6.1,622.0,[Charles Tait],...,"[0.6, 0.6]",5.0,0.60000,"[Charles Tait, Millard Johnson, Orrie Perry, R...","[0.6, 0.6, 0.6, 0.6, 0.6]",5.3,21,NaN,NaN,NaN
1,tt0000615,Robbery Under Arms,Robbery Under Arms,0,1907.0,60.0,[Drama],4.5,14.0,[Charles MacMahon],...,"[0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6]",2.0,0.60000,"[Charles MacMahon, C. Byers Coates]","[0.6, 0.6]",1.0,1,[Rolf Boldrewood],NaN,NaN
2,tt0000679,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays,0,1908.0,120.0,"[Adventure, Fantasy]",5.2,35.0,"[Francis Boggs, Otis Turner]",...,"[1.4, 1.237, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6...",4.0,0.81625,"[L. Frank Baum, Francis Boggs, Otis Turner, Na...","[1.237, 0.828, 0.6, 0.6]",1.0,1,[L. Frank Baum],NaN,NaN
3,tt0000846,Un día en Xochimilco,Un día en Xochimilco,0,1909.0,0.0,NaN,NaN,NaN,[Hermanos Alva],...,NaN,NaN,NaN,NaN,NaN,5.0,1,NaN,NaN,NaN
4,tt0000867,Fiesta de toros,Fiesta de toros,0,1909.0,0.0,NaN,NaN,NaN,[Hermanos Alva],...,NaN,NaN,NaN,NaN,NaN,5.0,1,NaN,NaN,NaN

In [4]:
# get 50 sample movies
sample_db = function.get_combined(sample_size=50)
sample_db.head(5)

,_id,primaryTitle,originalTitle,isAdult,release_year,runtimeMinutes,genres,imdb_avgRating,imdb_numVotes,Directors,...,num_of_cast,top_10_cast_popularity_mean,top_10_cast_popularity,num_of_crew,top_10_crew_popularity_mean,crews,top_10_crew_popularity,tmdb_avgRating,tmdb_numVotes,Writers
0,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,0,1906.0,70.0,"[Action, Adventure, Biography, History, Drama,...",6.1,622.0,[Charles Tait],...,2.0,0.6000,"[0.6, 0.6]",5.0,0.60000,"[Charles Tait, Millard Johnson, Orrie Perry, R...","[0.6, 0.6, 0.6, 0.6, 0.6]",5.3,21,NaN
1,tt0000615,Robbery Under Arms,Robbery Under Arms,0,1907.0,60.0,[Drama],4.5,14.0,[Charles MacMahon],...,8.0,0.6000,"[0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6]",2.0,0.60000,"[Charles MacMahon, C. Byers Coates]","[0.6, 0.6]",1.0,1,[Rolf Boldrewood]
2,tt0000679,The Fairylogue and Radio-Plays,The Fairylogue and Radio-Plays,0,1908.0,120.0,"[Adventure, Fantasy]",5.2,35.0,"[Francis Boggs, Otis Turner]",...,11.0,0.7437,"[1.4, 1.237, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6...",4.0,0.81625,"[L. Frank Baum, Francis Boggs, Otis Turner, Na...","[1.237, 0.828, 0.6, 0.6]",1.0,1,[L. Frank Baum]
3,tt0000846,Un día en Xochimilco,Un día en Xochimilco,0,1909.0,0.0,NaN,NaN,NaN,[Hermanos Alva],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1,NaN
4,tt0000867,Fiesta de toros,Fiesta de toros,0,1909.0,0.0,NaN,NaN,NaN,[Hermanos Alva],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1,NaN

In [5]:
# get movies later than 1960
new_db = function.get_combined(release_year_cutoff=1960)
new_db.head(5)

,_id,primaryTitle,originalTitle,isAdult,release_year,runtimeMinutes,genres,imdb_avgRating,imdb_numVotes,Directors,...,num_of_crew,top_10_crew_popularity_mean,crews,top_10_crew_popularity,tmdb_avgRating,tmdb_numVotes,release_year_int,homepage,tagline,belongs_to_collection
0,tt0011216,Spanish Fiesta,La fête espagnole,0,2019.0,67.0,[Drama],6.6,22.0,[Germaine Dulac],...,5.0,0.676000,"[Germaine Dulac, Serge Sandberg, Paul Parguel,...","[0.98, 0.6, 0.6, 0.6, 0.6]",6.0,1,2019,NaN,NaN,NaN
1,tt0011801,Tötet nicht mehr,Tötet nicht mehr,0,2019.0,127.0,"[Action, Crime, Drama]",NaN,NaN,None,...,6.0,0.733333,"[Gerhard Lamprecht, Willi Herrmann, Lupu Pick,...","[1.4, 0.6, 0.6, 0.6, 0.6, 0.6]",0.0,0,2019,NaN,NaN,NaN
2,tt0015414,La tierra de los toros,La tierra de los toros,0,2000.0,60.0,[Drama],5.4,11.0,Musidora,...,1.0,0.600000,[Musidora],[0.6],0.0,0,2000,NaN,NaN,NaN
3,tt0015724,Dama de noche,Dama de noche,0,1993.0,102.0,"[Drama, Mystery, Romance, Thriller]",6.0,21.0,"[Eva López Sánchez, None]",...,6.0,0.784667,"[Rodrigo Prieto, Hubert Barrero, Eva López Sán...","[1.708, 0.6, 0.6, 0.6, 0.6, 0.6]",8.8,4,1993,http://www.elccc.com.mx/sitio/index.php/produc...,NaN,NaN
4,tt0016906,Frivolinas,Frivolinas,0,2014.0,80.0,"[Comedy, Musical]",5.6,15.0,[Arturo Carballo],...,2.0,0.600000,"[Arturo Carballo, Ramón de Baños]","[0.6, 0.6]",0.0,0,2014,NaN,NaN,NaN

In [6]:
# get all possible column names
print(function.get_all_columns_name())

['_id', 'primaryTitle', 'originalTitle', 'isAdult', 'release_year', 'release_date', 'runtimeMinutes', 'genres', 'imdb_avgRating', 'imdb_numVotes', 'Directors', 'casts', 'tmdb_id', 'poster_path', 'original_language', 'popularity', 'budget', 'revenue', 'status', 'tagline', 'overview', 'company_name', 'keywords_name', 'num_of_cast', 'top_10_cast_popularity_mean', 'top_10_cast_popularity', 'num_of_crew', 'top_10_crew_popularity_mean', 'crews', 'top_10_crew_popularity', 'tmdb_avgRating', 'tmdb_numVotes', 'Writers', 'homepage', 'belongs_to_collection']

In [7]:
# drop selected columns to reduce query size
drop_cols = ['overview', 'tagline', 'originalTitle', 'num_of_cast', 'top_10_cast_popularity_mean'
             , 'top_10_cast_popularity', 'num_of_crew', 'top_10_crew_popularity_mean', 'crews'
             , 'top_10_crew_popularity', 'homepage']
dropped_db = function.get_combined(drop_lst=drop_cols)
dropped_db.head(5)

,_id,primaryTitle,isAdult,release_year,runtimeMinutes,genres,imdb_avgRating,imdb_numVotes,Directors,casts,...,budget,revenue,status,release_date,company_name,keywords_name,tmdb_avgRating,tmdb_numVotes,Writers,belongs_to_collection
0,tt0000574,The Story of the Kelly Gang,0,1906.0,70.0,"[Action, Adventure, Biography, History, Drama,...",6.1,622.0,[Charles Tait],"[Elizabeth Tait, John Tait]",...,0,0,Released,1906-12-26,"[Johnson and Gibson, J. & N. Tait]","[silent film, partially lost film]",5.3,21,NaN,NaN
1,tt0000615,Robbery Under Arms,0,1907.0,60.0,[Drama],4.5,14.0,[Charles MacMahon],"[Jim Gerald, J. Williams, George Merriman, Lan...",...,0,0,Released,1907-10-01,[MacMahon's Exquisite Pictures],NaN,1.0,1,[Rolf Boldrewood],NaN
2,tt0000679,The Fairylogue and Radio-Plays,0,1908.0,120.0,"[Adventure, Fantasy]",5.2,35.0,"[Francis Boggs, Otis Turner]","[Frank Burns, L. Frank Baum, George E. Wilson,...",...,0,0,Released,1908-09-23,[The Radio Play Company of America],[silent film],1.0,1,[L. Frank Baum],NaN
3,tt0000846,Un día en Xochimilco,0,1909.0,0.0,NaN,NaN,NaN,[Hermanos Alva],NaN,...,0,0,Released,1909-01-01,NaN,NaN,5.0,1,NaN,NaN
4,tt0000867,Fiesta de toros,0,1909.0,0.0,NaN,NaN,NaN,[Hermanos Alva],NaN,...,0,0,Released,1909-01-01,NaN,NaN,5.0,1,NaN,NaN

In [8]:
function.get_combined(1980, drop_cols, 100)

,_id,primaryTitle,isAdult,release_year,runtimeMinutes,genres,imdb_avgRating,imdb_numVotes,Directors,Writers,...,budget,revenue,status,release_date,company_name,keywords_name,tmdb_avgRating,tmdb_numVotes,release_year_int,belongs_to_collection
0,tt0011216,Spanish Fiesta,0,2019.0,67.0,[Drama],6.6,22.0,[Germaine Dulac],[Louis Delluc],...,0,0,Released,1920-01-01,[Les Films Louis Nalpas],"[woman director, partially lost film]",6.0,1,2019,NaN
1,tt0011801,Tötet nicht mehr,0,2019.0,127.0,"[Action, Crime, Drama]",NaN,NaN,None,[Gerhard Lamprecht],...,0,0,Released,1919-01-01,[Rex-Film GmbH],NaN,0.0,0,2019,NaN
2,tt0015414,La tierra de los toros,0,2000.0,60.0,[Drama],5.4,11.0,Musidora,NaN,...,0,0,Released,1924-01-01,[Musidora Films],[woman director],0.0,0,2000,NaN
3,tt0015724,Dama de noche,0,1993.0,102.0,"[Drama, Mystery, Romance, Thriller]",6.0,21.0,"[Eva López Sánchez, None]","[David Martin del Campo, Hubert Barrero]",...,0,0,Released,1993-05-18,[Centro de Capacitación Cinematográfica (CCC)],NaN,8.8,4,1993,NaN
4,tt0016906,Frivolinas,0,2014.0,80.0,"[Comedy, Musical]",5.6,15.0,[Arturo Carballo],NaN,...,0,0,Released,1926-01-01,[Ediciones Seleccionadas Arturo Carballo],NaN,0.0,0,2014,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,tt0078726,The Eight Escorts,0,1980.0,99.0,"[Action, Mystery]",5.3,26.0,"[Hsueh-Li Pao, Pao Hsueh-Li]","[Kuang Ni, Shu-Mei Chin, Yu Chu]",...,0,0,Released,1980-01-01,NaN,NaN,0.0,0,1980,NaN
96,tt0078732,Action,0,1980.0,121.0,[Drama],4.9,282.0,"[Tinto Brass, None]","[Gian Carlo Fusco, Roberto Lerici]",...,0,0,Released,1980-01-04,[Attori Registi Solidali (A.R.S.)],NaN,4.4,10,1980,NaN
97,tt0078749,Alien 2: On Earth,0,1980.0,92.0,"[Adventure, Horror, Sci-Fi, Science Fiction]",3.7,1275.0,"[Biagio Proietti, Ciro Ippolito]","[Ciro Ippolito, Biagio Proietti]",...,0,0,Released,1980-04-11,[GPS],"[child murder, cave, exploitation, psychic pow...",2.8,33,1980,NaN
98,tt0078751,Alison's Birthday,0,1981.0,97.0,[Horror],5.3,320.0,[Ian Coughlan],[Ian Coughlan],...,0,0,Released,1981-05-01,"[David Hannay Productions, Australian Film Com...",NaN,4.0,2,1981,NaN
99,tt0078765,The American Success Company,0,1980.0,91.0,"[Comedy, Drama]",5.7,298.0,[William Richert],"[Larry Cohen, William Richert]",...,0,0,Released,1980-03-01,"[Columbia Pictures, NF Geria II Filmgesellscha...",NaN,7.2,2,1980,NaN

In [9]:
movieLens_db = function.get_movieLens()
movieLens_db.head(5)

,_id,movieLens_Id,title,genres,tmdbId,individual_ratings,avg_rating
0,tt114709,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,862.0,"[4.0, 4.0, 4.5, 2.5, 4.5, 3.5, 4.0, 3.5, 3.0, ...",3.920930
1,tt113497,2,Jumanji (1995),Adventure|Children|Fantasy,8844.0,"[4.0, 4.0, 3.0, 3.0, 3.0, 3.5, 4.0, 4.5, 4.0, ...",3.431818
2,tt113228,3,Grumpier Old Men (1995),Comedy|Romance,15602.0,"[4.0, 5.0, 3.0, 3.0, 4.0, 5.0, 3.0, 4.0, 3.0, ...",3.259615
3,tt114885,4,Waiting to Exhale (1995),Comedy|Drama|Romance,31357.0,"[3.0, 3.0, 3.0, 3.0, 1.0, 2.0, 1.5]",2.357143
4,tt113041,5,Father of the Bride Part II (1995),Comedy,11862.0,"[5.0, 3.0, 5.0, 3.0, 4.0, 4.0, 2.0, 3.0, 4.0, ...",3.071429

In [10]:
movieLens_reviews_db = function.get_movieLens_reviews()
movieLens_reviews_db.head(5)

   userId  movieLens_Id  rating   timestamp  imdbId
0       1             1     4.0   964982703  114709
1       5             1     4.0   847434962  114709
2       7             1     4.5  1106635946  114709
3      15             1     2.5  1510577970  114709
4      17             1     4.5  1305696483  114709

In [11]:
df = function.get_combined(2010, drop_cols)

In [12]:
df

,_id,primaryTitle,isAdult,release_year,runtimeMinutes,genres,imdb_avgRating,imdb_numVotes,Directors,Writers,...,budget,revenue,status,release_date,company_name,keywords_name,tmdb_avgRating,tmdb_numVotes,release_year_int,belongs_to_collection
0,tt0011216,Spanish Fiesta,0,2019.0,67.0,[Drama],6.6,22.0,[Germaine Dulac],[Louis Delluc],...,0,0,Released,1920-01-01,[Les Films Louis Nalpas],"[woman director, partially lost film]",6.0,1,2019,NaN
1,tt0011801,Tötet nicht mehr,0,2019.0,127.0,"[Action, Crime, Drama]",NaN,NaN,None,[Gerhard Lamprecht],...,0,0,Released,1919-01-01,[Rex-Film GmbH],NaN,0.0,0,2019,NaN
2,tt0016906,Frivolinas,0,2014.0,80.0,"[Comedy, Musical]",5.6,15.0,[Arturo Carballo],NaN,...,0,0,Released,1926-01-01,[Ediciones Seleccionadas Arturo Carballo],NaN,0.0,0,2014,NaN
3,tt0019996,Hongxia,0,2011.0,94.0,[Action],6.3,52.0,Wen Yi-Min,NaN,...,0,0,Released,1929-07-11,[Youlian Film Company],NaN,6.3,3,2011,NaN
4,tt0062336,El Tango del Viudo y Su Espejo Deformante,0,2020.0,70.0,"[Drama, Fantasy, Horror]",6.3,135.0,"[Raoul Ruiz, Valeria Sarmiento, None]","[Omar Saavedra Santis, Daphne du Maurier, Galu...",...,0,0,Released,2020-02-21,[Poetastros],NaN,5.5,2,2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73658,tt7550498,Opasnyy soblazn,0,2020.0,NaN,"[Crime, Thriller]",NaN,NaN,"[Vladimir Chubrikov, None]",[Eva Istomina],...,0,0,Planned,NaN,[Viper Group Production],NaN,0.0,0,2020,NaN
73659,tt7550576,Tim & Faith: Soul2Soul,0,2017.0,102.0,"[Documentary, Music]",7.6,59.0,"[Dan Cutforth, Jane Lipsitz]",NaN,...,0,0,Released,2017-11-17,[Sho Films],NaN,8.0,2,2017,NaN
73660,tt7550632,The Barker,0,2017.0,76.0,"[Comedy, Action, Romance]",6.7,24.0,[Dennis Padilla],[Arlyn Dela Cruz],...,0,0,Released,2017-10-25,"[Viva Films, Blank Pages Productions]",[philippines],8.0,1,2017,NaN
73661,tt7550816,Ram Ratan,0,2017.0,112.0,[Romance],3.9,60.0,[Govind Sakariya],"[Praful Parekh, Anwar Shah]",...,0,0,Released,2017-06-12,NaN,NaN,6.0,1,2017,NaN
73662,tt7550952,Hürkus,0,2018.0,113.0,"[Biography, History, War]",5.8,1040.0,[Kudret Sabanci],"[Savas Korkmaz, Ufuk Bayram]",...,0,0,Released,2018-05-25,[Eğrikapı Productions],"[biography, history, based on real person]",4.3,3,2018,NaN

## Functions for inserting ML models

In [ ]:
# import pickle
# dbfile = open('random_forest_model.pkl', 'rb') 
# model = pickle.load(dbfile)
# p_model = pickle.dumps(model)
# type(p_model)

In [ ]:
model = YOUR MODEL
p_model = pickle.dumps(model)
type(p_model)

In [3]:
#model_type = "context", "collab", "rating"
function.store_model(trained_model=p_model, model_type="rating", note="Rating prediction: Max Xu Version 1")

606f8ef6d6be74b602dcdd24

In [3]:
#model_type = "context", "collab", "rating"
model_from_db = function.get_model(model_type="rating", Description="Rating prediction: Max Xu Version 1")

returned a New Film Rating Prediction model, which was created at 04/08/2021, 23:17:51
Note on the model: Rating prediction: Max Xu Version 1

In [4]:
model_from_db

RandomForestRegressor(max_features=0.15000000000000002, min_samples_leaf=6,
                      min_samples_split=16)