In [2]:
import pickle
import numpy as np
import pandas as pd
import os
import sys
module_path = os.path.abspath(os.path.join('./code'))
if module_path not in sys.path:
    sys.path.append(module_path)
from similarity import SimilarityPredictions

In [22]:
movies_with_tag = pd.read_csv('data/all_movies.csv', lineterminator='\n')
movies_with_tag_movie_index = pd.read_csv('data/all_movies-movie-index.csv', lineterminator='\n')
movies_with_rating = pd.read_csv('data/all_movies_with_rating.csv', lineterminator='\n')
movies_with_movie_index_rating = pd.read_csv('data/all_movies_movie_index_rating.csv', lineterminator='\n')

In [9]:
movies_with_rating.head()

,primaryTitle,Directors,Writers,tmdb_id,company_name,movieId,genres,ratings_count,avg_rating
0,Kate & Leopold,James Mangold None,Steven Rogers,11232,Konrad Pictures Miramax,80,Comedy Romance,4178,3.155936
1,The Other Side of the Wind,Orson Welles None,Dax Phelan,299782,SACI Les Films de l'Astrophore,13231,Comedy Drama,9,2.444444
2,Crime and Punishment,Menahem Golan None,Fyodor Dostoevsky Ivan Mendzheritskiy,109809,NaN,21528,Drama,1,1.000000
3,Master i Margarita,Yuriy Kara,Mikhail A. Bulgakov Felix Kroll,63163,Tvorcheskaya Assotsiatsiya Mezhdunarodnykh Pro...,14074,Drama Fantasy Mystery Romance,10,3.200000
4,The Fantasticks,Michael Ritchie,Harvey Schmidt Tom Jones,62127,Sullivan Street Productions Michael Ritchie Pr...,7948,Musical,95,2.921053

In [27]:
movies_with_movie_index_rating.drop(['movieId_x', 'movieId_y'], axis=1, inplace=True)

In [4]:
movies_with_tag.shape

(21639, 13)

In [5]:
movies_with_tag_movie_index.shape

(21639, 11)

In [19]:
movies_with_tag_movie_index.head()

,primaryTitle,Directors,Writers,tmdb_id,popularity,company_name,tmdb_avgRating,release_year_int,title,genres,document
0,Hollow Man,Paul Verhoeven,Gary Scott Thompson Andrew W. Marlowe Ron Vign...,9383,20.352,Columbia Pictures Red Wagon Entertainment Glob...,5.9,2000,Hollow Man (2000),Horror Sci-Fi Thriller,Paul Verhoeven Rhona Mitra Elisabeth Shue Kevi...
1,Nurse Betty,Neil LaBute None,James Flamberg John C. Richards Neil LaBute,10480,12.417,IMF Internationale Medien und Film GmbH & Co. ...,6.0,2000,Nurse Betty (2000),Comedy Crime Drama Romance Thriller,Neil LaBute None Morgan Freeman Ren√©e Zellwege...
2,Supernova,Walter Hill,William Malone David C. Wilson Daniel Chuba Sy...,10384,13.120,Hammerhead Productions Screenland Pictures Uni...,5.0,2000,Supernova (2000),Adventure Sci-Fi Thriller,Walter Hill James Spader Robin Tunney Angela B...
3,Boiler Room,Ben Younger None,Ben Younger,14181,10.375,New Line Cinema,6.7,2000,Boiler Room (2000),Crime Drama Thriller,Ben Younger None Ben Affleck Vin Diesel Giovan...
4,Pitch Black,David Twohy None,Ken Wheat Jim Wheat David Twohy Jason Brubaker...,2787,16.980,Interscope Communications,6.8,2000,Pitch Black (2000),Horror Sci-Fi Thriller,David Twohy None Vin Diesel Claudia Black Keit...

In [6]:
movies_with_tag[movies_with_tag['primaryTitle'].str.contains('Lord of the Rings')]

,index,primaryTitle,Directors,Writers,tmdb_id,popularity,company_name,tmdb_avgRating,release_year_int,movieId,title,genres,document
22,22,The Lord of the Rings: The Fellowship of the Ring,Peter Jackson None,J.R.R. Tolkien Fran Walsh Philippa Boyens,120,77.541,New Line Cinema WingNut Films The Saul Zaentz ...,8.3,2001,81,"Lord of the Rings: The Fellowship of the Ring,...",Adventure Fantasy,Peter Jackson None Sean Bean Cate Blanchett El...
149,149,The Lord of the Rings: The Return of the King,Peter Jackson None,J.R.R. Tolkien Fran Walsh Philippa Boyens,122,67.803,New Line Cinema WingNut Films The Saul Zaentz ...,8.5,2003,157,"Lord of the Rings: The Return of the King, The...",Action Adventure Drama Fantasy,Peter Jackson None Sean Bean Cate Blanchett Mi...
150,150,The Lord of the Rings: The Two Towers,Peter Jackson None,J.R.R. Tolkien Fran Walsh Stephen Sinclair Phi...,121,67.340,New Line Cinema WingNut Films The Saul Zaentz ...,8.3,2002,116,"Lord of the Rings: The Two Towers, The (2002)",Adventure Fantasy,Peter Jackson None Sean Bean Cate Blanchett Mi...

In [7]:
movies_with_tag[movies_with_tag['primaryTitle'].str.contains('Inception')]

,index,primaryTitle,Directors,Writers,tmdb_id,popularity,company_name,tmdb_avgRating,release_year_int,movieId,title,genres,document
9965,9965,Inception,Christopher Nolan,Gabriel Hardman Lauren Fash,27205,62.877,Legendary Pictures Syncopy Warner Bros. Pictures,8.3,2010,305,Inception (2010),Action Crime Drama Mystery Sci-Fi Thriller IMAX,Christopher Nolan Leonardo DiCaprio Tom Hardy ...

In [20]:
movies_with_tag[movies_with_tag['primaryTitle'].str.contains('3 Idiots')]

,index,primaryTitle,Directors,Writers,tmdb_id,popularity,company_name,tmdb_avgRating,release_year_int,movieId,title,genres,document
8690,8690,3 Idiots,Rajkumar Hirani None,Vidhu Vinod Chopra Abhijat Joshi Chetan Bhagat...,20453,18.011,Vidhu Vinod Chopra Productions Vinod Chopra Films,8.0,2009,1847,3 Idiots (2009),Comedy Drama Romance,Rajkumar Hirani None Boman Irani Ali Fazal Mon...

In [23]:
movies_with_tag[movies_with_tag['primaryTitle'].str.contains('Avenger')]

,index,primaryTitle,Directors,Writers,tmdb_id,popularity,company_name,tmdb_avgRating,release_year_int,movieId,title,genres,document
461,461,Citizen Toxie: The Toxic Avenger IV,Lloyd Kaufman None,Trent Haaga Patrick Cassidy Matt Levin Gabriel...,27601,10.559,Troma Entertainment,6.6,2000,8351,Citizen Toxie: The Toxic Avenger IV (2000),Action Comedy Horror,Lloyd Kaufman None Ron Jeremy Stan Lee Julie S...
5176,5176,Captain America: The First Avenger,Joe Johnston None,Jack Kirby Joe Simon Christopher Markus Stephe...,1771,69.605,Marvel Studios Paramount Marvel Entertainment,6.9,2011,1136,Captain America: The First Avenger (2011),Action Adventure Sci-Fi Thriller War,Joe Johnston None Sebastian Stan Samuel L. Jac...
6787,6787,The Avengers,Joss Whedon None,Zak Penn Stan Lee Joss Whedon Jack Kirby Bryan...,24428,151.451,Marvel Studios Paramount,7.7,2012,318,"Avengers, The (2012)",Action Adventure Sci-Fi IMAX,Joss Whedon None Scarlett Johansson Robert Dow...
18480,18480,Avengers: Infinity War,Joe Russo Anthony Russo,Jack Kirby Stan Lee Christopher Markus Stephen...,299536,329.147,Marvel Studios,8.3,2018,477,Avengers: Infinity War - Part I (2018),Action Adventure Sci-Fi,Joe Russo Anthony Russo Scarlett Johansson Seb...

In [8]:
movies_with_tag_movie_index[movies_with_tag_movie_index['primaryTitle'].str.contains('Lord of the Rings')]

,primaryTitle,Directors,Writers,tmdb_id,popularity,company_name,tmdb_avgRating,release_year_int,title,genres,document
81,The Lord of the Rings: The Fellowship of the Ring,Peter Jackson None,J.R.R. Tolkien Fran Walsh Philippa Boyens,120,77.541,New Line Cinema WingNut Films The Saul Zaentz ...,8.3,2001,"Lord of the Rings: The Fellowship of the Ring,...",Adventure Fantasy,Peter Jackson None Sean Bean Cate Blanchett El...
116,The Lord of the Rings: The Two Towers,Peter Jackson None,J.R.R. Tolkien Fran Walsh Stephen Sinclair Phi...,121,67.340,New Line Cinema WingNut Films The Saul Zaentz ...,8.3,2002,"Lord of the Rings: The Two Towers, The (2002)",Adventure Fantasy,Peter Jackson None Sean Bean Cate Blanchett Mi...
157,The Lord of the Rings: The Return of the King,Peter Jackson None,J.R.R. Tolkien Fran Walsh Philippa Boyens,122,67.803,New Line Cinema WingNut Films The Saul Zaentz ...,8.5,2003,"Lord of the Rings: The Return of the King, The...",Action Adventure Drama Fantasy,Peter Jackson None Sean Bean Cate Blanchett Mi...

In [9]:
movies_with_tag_movie_index[movies_with_tag_movie_index['primaryTitle'].str.contains('Inception')]

,primaryTitle,Directors,Writers,tmdb_id,popularity,company_name,tmdb_avgRating,release_year_int,title,genres,document
305,Inception,Christopher Nolan,Gabriel Hardman Lauren Fash,27205,62.877,Legendary Pictures Syncopy Warner Bros. Pictures,8.3,2010,Inception (2010),Action Crime Drama Mystery Sci-Fi Thriller IMAX,Christopher Nolan Leonardo DiCaprio Tom Hardy ...

In [18]:
movies_with_tag_movie_index[movies_with_tag_movie_index['primaryTitle'].str.contains('3 Idiots')]

,primaryTitle,Directors,Writers,tmdb_id,popularity,company_name,tmdb_avgRating,release_year_int,title,genres,document
1847,3 Idiots,Rajkumar Hirani None,Vidhu Vinod Chopra Abhijat Joshi Chetan Bhagat...,20453,18.011,Vidhu Vinod Chopra Productions Vinod Chopra Films,8.0,2009,3 Idiots (2009),Comedy Drama Romance,Rajkumar Hirani None Boman Irani Ali Fazal Mon...

In [25]:
movies_with_tag_movie_index[movies_with_tag_movie_index['primaryTitle'].str.contains('Avenger')]

,primaryTitle,Directors,Writers,tmdb_id,popularity,company_name,tmdb_avgRating,release_year_int,title,genres,document
318,The Avengers,Joss Whedon None,Zak Penn Stan Lee Joss Whedon Jack Kirby Bryan...,24428,151.451,Marvel Studios Paramount,7.7,2012,"Avengers, The (2012)",Action Adventure Sci-Fi IMAX,Joss Whedon None Scarlett Johansson Robert Dow...
477,Avengers: Infinity War,Joe Russo Anthony Russo,Jack Kirby Stan Lee Christopher Markus Stephen...,299536,329.147,Marvel Studios,8.3,2018,Avengers: Infinity War - Part I (2018),Action Adventure Sci-Fi,Joe Russo Anthony Russo Scarlett Johansson Seb...
1136,Captain America: The First Avenger,Joe Johnston None,Jack Kirby Joe Simon Christopher Markus Stephe...,1771,69.605,Marvel Studios Paramount Marvel Entertainment,6.9,2011,Captain America: The First Avenger (2011),Action Adventure Sci-Fi Thriller War,Joe Johnston None Sebastian Stan Samuel L. Jac...
8351,Citizen Toxie: The Toxic Avenger IV,Lloyd Kaufman None,Trent Haaga Patrick Cassidy Matt Levin Gabriel...,27601,10.559,Troma Entertainment,6.6,2000,Citizen Toxie: The Toxic Avenger IV (2000),Action Comedy Horror,Lloyd Kaufman None Ron Jeremy Stan Lee Julie S...

In [10]:
content_embeddings_with_tag_idx = pd.read_pickle("./pkl/autoencoder_embeddings-with-tag-index.pkl")
content_embeddings_with_tag_idx = pd.DataFrame(content_embeddings_with_tag_idx)
print(content_embeddings_with_tag_idx.shape)
content_embeddings_with_tag_idx.head()

(21639, 100)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
1,0.0,0.0,0.000000,0.621931,0.0,0.0,0.0,0.0,0.271537,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
2,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.594124,0.0,...,0.0,0.201731,0.0,0.0,0.0,0.0,0.0,0.0,0.347761,0.000000
3,0.0,0.0,0.000000,1.991568,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.440755
4,0.0,0.0,0.069976,0.460829,0.0,0.0,0.0,0.0,0.272096,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000

In [11]:
content_embeddings_with_movie_idx = pd.read_pickle("./pkl/autoencoder_embeddings-movie-index.pkl")
content_embeddings_with_movie_idx = pd.DataFrame(content_embeddings_with_movie_idx)
print(content_embeddings_with_movie_idx.shape)
content_embeddings_with_movie_idx.head()

(21639, 100)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.307730,0.0,0.0,...,0.0,0.0,0.531797,0.000000,0.632206,0.0,0.0,0.00000,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.000000,0.000000,0.275598,0.0,0.0,0.00000,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.100161,0.000000,0.348727,0.0,0.0,0.00641,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.157886,0.0,0.0,...,0.0,0.0,0.502684,0.368243,0.135098,0.0,0.0,0.00000,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.259404,0.000000,0.328752,0.0,0.0,0.00000,0.0,0.0

In [12]:
collaborative_embeddings_2 = pd.read_pickle("./pkl/nn_embeddings_2.pkl")
collaborative_embeddings_2 = pd.DataFrame(collaborative_embeddings_2)
print(collaborative_embeddings_2.shape)
collaborative_embeddings_2.head()

(21639, 100)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.180236,-0.043935,0.043850,-0.111843,-0.018668,-0.052892,-0.157531,0.210268,-0.044680,0.123572,...,0.122363,0.047981,-0.040833,-0.116958,0.130361,-0.008938,-0.042715,0.037321,0.097398,-0.044288
1,-0.006692,-0.078064,0.031268,0.002688,-0.089660,-0.038941,-0.041501,0.003827,-0.094820,-0.010475,...,-0.080280,-0.014104,0.005555,0.034117,-0.059089,0.053237,0.033376,0.005963,0.036301,-0.071273
2,0.038863,0.013770,0.006863,-0.128206,0.023429,0.010521,0.050968,0.095122,-0.010426,-0.039181,...,0.071861,0.061515,-0.008856,-0.060817,0.124664,-0.082715,-0.108586,0.036938,0.090289,0.034027
3,-0.025671,-0.030430,0.061868,0.073042,-0.074818,-0.091832,0.025247,-0.049206,-0.076967,0.044723,...,-0.026670,-0.097335,-0.065033,0.023394,-0.033668,0.044048,0.108960,0.001341,-0.067678,-0.083032
4,-0.030464,-0.063205,0.047684,0.089612,0.043399,-0.050626,-0.022222,-0.051559,0.028215,0.049484,...,0.015663,-0.066348,-0.018772,0.103852,-0.042132,0.113786,0.141700,-0.037729,0.005843,0.025250

In [13]:
collaborative_embeddings_3 = pd.read_pickle("./pkl/nn_embeddings_3.pkl")
collaborative_embeddings_3 = pd.DataFrame(collaborative_embeddings_3)
print(collaborative_embeddings_3.shape)
collaborative_embeddings_3.head()

(21639, 100)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.007803,-0.012166,0.101375,-0.066157,-0.005612,-0.032284,0.018015,0.099990,0.016905,0.053393,...,0.127777,0.102762,-0.040962,-0.197559,0.072720,-0.106867,-0.091647,-0.126125,0.063235,0.021663
1,-0.001053,0.121650,0.104060,-0.016005,-0.004826,0.028206,-0.006742,-0.033284,0.091780,0.024877,...,-0.051970,0.091312,-0.035859,0.031048,0.058001,-0.031353,-0.071744,0.003846,-0.052685,-0.025805
2,-0.035649,0.032740,0.030359,-0.055056,-0.053185,-0.020223,0.025921,0.093321,0.047292,0.021516,...,0.126401,0.053919,0.000637,-0.019367,0.058068,-0.087162,-0.019203,-0.037321,0.088823,-0.019213
3,-0.002039,0.040073,0.005732,-0.010510,-0.037414,0.003133,-0.031116,-0.002286,0.001332,0.017818,...,-0.039781,-0.048871,-0.021756,0.084140,-0.008864,-0.040365,0.119574,-0.021103,0.061899,0.013205
4,0.015491,-0.025321,-0.028692,0.097393,0.004820,-0.016084,-0.086690,-0.105571,0.056060,-0.004892,...,-0.121349,-0.094026,-0.084806,0.067358,-0.000175,0.025376,0.007887,0.017351,-0.080474,0.074166

In [37]:
def get_recs(movie_id, embeddings, df):
    #get similar movies
    sim_model = SimilarityPredictions(embeddings, similarity_metric="cosine")
    output = sim_model.predict_similar_items(seed_item=movie_id, n=20)
    similar_movies = pd.DataFrame(output)
    similar_movies.set_index('item_id', inplace=True)
    sim_df = pd.merge(df, similar_movies, left_index=True, right_index=True)
#     sim_df = pd.merge(df, similar_movies, left_on='movieId', right_index=True)
    sim_df.sort_values('similarity_score', ascending=False, inplace=True)
    
    #save recs locally
#     sim_df.head(20).to_csv(file_path, index=False, header=True)
    return sim_df.head(10)

In [8]:
get_recs(9965, collaborative_embeddings, movies_with_tag)

,index,primaryTitle,Directors,Writers,tmdb_id,popularity,company_name,tmdb_avgRating,release_year_int,movieId,title,genres,document,similarity_score
9965,9965,Inception,Christopher Nolan,Gabriel Hardman Lauren Fash,27205,62.877,Legendary Pictures Syncopy Warner Bros. Pictures,8.3,2010,305,Inception (2010),Action Crime Drama Mystery Sci-Fi Thriller IMAX,Christopher Nolan Leonardo DiCaprio Tom Hardy ...,1.000000
17226,17226,The Midnight After,Fruit Chan None,Fai-Hung Chan Ho-Yan Kong Pizza Kong Hiu-Yan,254526,4.356,NaN,5.9,2014,9745,The Midnight After (2014),Comedy Sci-Fi Thriller,Fruit Chan None Kara Hui Janice Man Simon Yam ...,0.726522
3552,3552,Heights,Chris Terrio,Amy Fox Chris Terrio,29080,6.713,Merchant Ivory Productions,6.8,2005,5551,Heights (2004),Drama,Chris Terrio Elizabeth Banks James Marsden Mat...,0.710330
4385,4385,A Simple Curve,Aubrey Nealon,Aubrey Nealon,43756,5.858,British Columbia Film,5.7,2005,8683,A Simple Curve (2005),Drama,Aubrey Nealon Sarah Lind Matt Craven Michael H...,0.694416
3669,3669,Hitch,Andy Tennant,Kevin Bisch,8488,19.563,Columbia Pictures Overbrook Entertainment Sony...,6.5,2005,601,Hitch (2005),Comedy Romance,Andy Tennant Will Smith Paula Patton Amber Val...,0.691032
15596,15596,No Where No Body,Ebrahim Sheibani,Mohammad Reza Mouyini Amir Arabi Ahmad Moradpo...,388182,0.600,NaN,7.0,2013,15911,No Where No One (Hich Koja Hich Kas) (2013),Drama Romance,Ebrahim Sheibani Mohammad Reza Foroutan Saber ...,0.688156
7058,7058,Suite Fran√ßaise,Saul Dibb None,Ir√®ne N√©mirovsky Matt Charman,271674,13.887,TF1 Droits Audiovisuels SCOPE Pictures Canal+ ...,7.4,2014,8256,Suite Fran√ßaise (2015),Drama Romance War,Saul Dibb None Margot Robbie Kristin Scott Tho...,0.682731
1329,1329,Ik√≠ngut,G√≠sli Sn√¶r Erlingsson,Jon Steinar Ragnarsson,72661,0.841,NaN,0.0,2000,20393,Ikingut (2000),(no genres listed),G√≠sli Sn√¶r Erlingsson Orto Ignatiussen Jon Ste...,0.681744
6937,6937,L'auberge rouge,G√©rard Krawczyk,Claude Autant-Lara Jean Aurenche Pierre Bost M...,13732,6.707,Warner Bros. Pictures,5.2,2007,13844,The Red Inn (2007),Comedy,G√©rard Krawczyk Christian Clavier Josiane Bala...,0.681339
16157,16157,Let's Kill Ward's Wife,Scott Foley,NaN,300706,10.358,Lost Rhino Films,5.6,2014,6637,Let's Kill Ward's Wife (2014),Comedy,Scott Foley Patrick Wilson Scott Foley Dagmara...,0.679513

In [38]:
get_recs(9965, collaborative_embeddings_3, movies_with_rating)

,primaryTitle,Directors,Writers,tmdb_id,company_name,movieId,genres,ratings_count,avg_rating,similarity_score
9965,Inception,Christopher Nolan,Gabriel Hardman Lauren Fash,27205,Legendary Pictures Syncopy Warner Bros. Pictures,305,Action Crime Drama Mystery Sci-Fi Thriller IMAX,41475,4.162990,1.000000
15031,The Last of Robin Hood,Richard Glatzer Wash Westmoreland None,Wash Westmoreland,214091,Killer Films Big Indie Pictures A+E Studios Un...,12233,Drama,15,2.666667,0.784354
15778,Way Beyond Weight,Estela Renner,Marcos Nisti,165321,Maria Farinha Filmes,21288,Documentary,2,3.750000,0.781357
5159,Mr. Magorium's Wonder Emporium,Zach Helm None,Zach Helm,2284,Ontario Media Development Corporation (OMDC) M...,1827,Children Comedy Fantasy,817,3.203794,0.776156
13466,Mission Blue,Fisher Stevens Robert Nixon,Jack Youngelson Mark Monroe,286407,True Blue Films Insurgent Docs,11186,Documentary,18,3.694444,0.769813
5155,Evil Behind You,Jim Carroll Jason Kerr,NaN,134890,NaN,19939,Action Thriller,1,0.500000,0.764863
12203,Unicorn City,Bryan Lefler,Cameron Dayton Adrian Lefler,102051,NaN,8827,Comedy Romance,9,2.888889,0.762481
15089,Pazze di me,Fausto Brizzi,Marco Martani Michela Andreozzi Federica Bosco...,195544,Monte dei Paschi di Siena Wildside Rai Cinema ...,18999,Comedy,2,2.750000,0.760682
6463,In the City of Sylvia,Jos√© Luis Guer√≠n,NaN,29568,Eddie Saeta Ch√¢teau-Rouge Production,9688,Drama,30,3.250000,0.756468
9001,Puss,Johan Kling None,Johan Kling,56596,NaN,17013,(no genres listed),2,2.000000,0.746830

In [36]:
get_recs(9965, collaborative_embeddings_3, movies_with_rating)

,primaryTitle,Directors,Writers,tmdb_id,company_name,movieId,genres,ratings_count,avg_rating,similarity_score
11339,The Other Dream Team,Marius A. Markevicius,Jon Weinbach,84318,The Basketball Future Foundation Sorrento Prod...,9965,Documentary,26,3.653846,1.000000
10805,Harishchandrachi Factory,Paresh Mokashi,NaN,35572,NaN,15031,Comedy Drama,10,3.250000,0.784354
4756,Explosive City,Tak-Sam Leong Sam Leong Tak-Sam,NaN,32229,Art Port Inc,15778,Action,9,3.500000,0.781357
4034,Evilenko,David Grieco,David Grieco,46342,Pacific Pictures,5159,Crime Horror Thriller,9,3.388889,0.776156
20944,Astro,Asif Akbar None,Bernard Selling,526475,Film Life Factory Heartrock Pictures,13466,Action Sci-Fi Thriller,8,2.875000,0.769813
18075,Tales of the Grim Sleeper,Marc Hoeferlin Barney Broomfield Nick Broomfield,NaN,289575,South Central Films,5155,Crime Documentary,51,3.509804,0.764863
2220,Fellini: I'm a Born Liar,Damian Pettigrew,Olivier Gal,203252,ARTE Portrait & Cie Tele+ Dream Film Asylum Pi...,12203,Documentary,21,3.285714,0.762481
15372,Valentine Road,Marta Cunningham,NaN,159015,NaN,15089,Documentary,12,3.166667,0.760682
2882,The Far Side of the Moon,Robert Lepage,NaN,22618,Media Principia,6463,Drama,31,3.241935,0.756468
13622,The Ambassador,Mads Br√ºgger,Maja Jul Larsen,84172,Drafthouse Films,9001,Documentary,76,3.743421,0.746830

In [17]:
get_recs(305, collaborative_embeddings_3, movies_with_tag_movie_index)

,primaryTitle,Directors,Writers,tmdb_id,popularity,company_name,tmdb_avgRating,release_year_int,title,genres,document,similarity_score
305,Inception,Christopher Nolan,Gabriel Hardman Lauren Fash,27205,62.877,Legendary Pictures Syncopy Warner Bros. Pictures,8.3,2010,Inception (2010),Action Crime Drama Mystery Sci-Fi Thriller IMAX,Christopher Nolan Leonardo DiCaprio Tom Hardy ...,1.000000
297,The Secret in Their Eyes,Juan Jos√© Campanella,Eduardo Sacheri A√≠da Bortnik,25376,14.862,Canal+ Espa√±a 100 Bares Tornasol Films Ministe...,8.0,2009,"Secret in Their Eyes, The (El secreto de sus o...",Crime Drama Mystery Romance Thriller,Juan Jos√© Campanella Pablo Rago Ricardo Dar√≠n ...,0.800285
2175,Black Book,Paul Verhoeven None,Gerard Soeteman,9075,10.007,Studio Babelsberg Motel Films Motion Investmen...,7.5,2006,Black Book (Zwartboek) (2006),Drama Thriller War,Paul Verhoeven None Carice van Houten Matthias...,0.796103
576,About Time,Richard Curtis,Richard Curtis Emma Freud,122906,27.144,Working Title Films Translux Universal Picture...,7.9,2013,About Time (2013),Drama Fantasy Romance,Richard Curtis Margot Robbie Rachel McAdams Bi...,0.789830
3127,Why We Fight,Eugene Jarecki,NaN,14286,10.501,Charlotte Street Films,7.7,2005,Why We Fight (2005),Documentary,Eugene Jarecki Osama bin Laden George W. Bush ...,0.787181
350,Whiplash,Damien Chazelle None,Jasmine McGlade,244786,37.388,Bold Films Blumhouse Productions Right of Way ...,8.4,2014,Whiplash (2014),Drama,Damien Chazelle None Melissa Benoist J.K. Simm...,0.785032
1073,The Visitor,Tom McCarthy,NaN,12473,11.794,Overture Films,7.1,2007,"Visitor, The (2007)",Drama Romance,Tom McCarthy Richard Kind Danai Gurira Richard...,0.778045
511,Dig!,Ondi Timoner None,NaN,1843,8.032,Interloper Films,7.0,2004,DiG! (2004),Documentary,Ondi Timoner None Eric Hedford Anton Newcombe ...,0.778038
274,Spirited Away,Hayao Miyazaki,NaN,129,63.479,Studio Ghibli,8.5,2001,Spirited Away (Sen to Chihiro no kamikakushi) ...,Adventure Animation Fantasy,Hayao Miyazaki Bunta Sugawara Ken Yasuda Mari ...,0.776662
2824,Lagaan: Once Upon a Time in India,Ashutosh Gowariker None,Kumar Dave Sanjay Dayma K.P. Saxena,19666,10.153,Aamir Khan Productions Jhamu Sughand Productio...,7.4,2001,Lagaan: Once Upon a Time in India (2001),Comedy Drama Musical Romance,Ashutosh Gowariker None Amitabh Bachchan Jerem...,0.773432

In [31]:
get_recs(9965, content_embeddings_with_tag_idx, movies_with_rating)

,primaryTitle,Directors,Writers,tmdb_id,company_name,movieId,genres,ratings_count,avg_rating,similarity_score
9965,Inception,Christopher Nolan,Gabriel Hardman Lauren Fash,27205,Legendary Pictures Syncopy Warner Bros. Pictures,305,Action Crime Drama Mystery Sci-Fi Thriller IMAX,41475,4.162990,1.000000
709,Equilibrium,Kurt Wimmer None,Kurt Wimmer,7299,Blue Tulip Productions Dimension Films,113,Action Sci-Fi Thriller,10970,3.741841,0.984117
4646,V for Vendetta,James McTeigue None,Lilly Wachowski Lana Wachowski David Lloyd Ala...,752,Studio Babelsberg Virtual Studios Anarchos Pro...,220,Action Sci-Fi Thriller IMAX,27101,3.913287,0.981266
1740,The Butterfly Effect,Eric Bress J. Mackye Gruber None,Eric Bress J. Mackye Gruber,1954,FilmEngine Katalyst Films BenderSpink New Line...,276,Drama Sci-Fi Thriller,16342,3.711357,0.980789
8905,Limitless,Neil Burger,Leslie Dixon Alan Glynn,51876,Relativity Media Virgin Produced Many Rivers P...,308,Sci-Fi Thriller,9884,3.845913,0.979786
3494,Serenity,Joss Whedon,Joss Whedon Rpin Suwannath Ray Harvie,16320,Universal Pictures Barry Mendel Productions,367,Action Adventure Sci-Fi,12531,3.984000,0.977426
5068,Life of Pi,Ang Lee,David Magee Yann Martel Dean Georgaris,87827,Fox 2000 Pictures Dune Entertainment Ingenious...,332,Adventure Drama IMAX,7763,3.697540,0.976388
18058,Guardians of the Galaxy Vol. 2,James Gunn,Steve Englehart Jim Starlin Dan Abnett Andy La...,283995,Marvel Studios,2018,Action Adventure Sci-Fi,4942,3.859875,0.974959
5800,Mr. Nobody,Jaco Van Dormael,NaN,31011,Pan Europ√©enne Production Virtual Films Wild B...,1859,Drama Fantasy Romance Sci-Fi,3146,3.911316,0.971230
4756,Explosive City,Tak-Sam Leong Sam Leong Tak-Sam,NaN,32229,Art Port Inc,15778,Action,9,3.500000,0.970680

In [16]:
get_recs(305, content_embeddings_with_movie_idx, movies_with_tag_movie_index)

,primaryTitle,Directors,Writers,tmdb_id,popularity,company_name,tmdb_avgRating,release_year_int,title,genres,document,similarity_score
305,Inception,Christopher Nolan,Gabriel Hardman Lauren Fash,27205,62.877,Legendary Pictures Syncopy Warner Bros. Pictures,8.3,2010,Inception (2010),Action Crime Drama Mystery Sci-Fi Thriller IMAX,Christopher Nolan Leonardo DiCaprio Tom Hardy ...,1.000000
12485,God of War,Gordon Chan,Frankie Tam MengZhang Wu Maria Wong Zhaozheng ...,455043,22.289,Well Go USA Entertainment Media Asia Films,5.6,2017,God of War (2017),Action,Gordon Chan Sammo Hung Yasuaki Kurata Jiang Lu...,0.999708
571,Rise of the Planet of Apes,Rupert Wyatt None,Pierre Boulle Amanda Silver Rick Jaffa,61791,39.092,Dune Entertainment III Dune Entertainment Cher...,7.3,2011,Rise of the Planet of the Apes (2011),Action Drama Sci-Fi Thriller,Rupert Wyatt None B. J. Harrison Andy Serkis T...,0.998862
4552,Saint Ralph,Michael McGowan,NaN,25248,6.800,Running Miracles Productions Alliance Atlantis...,7.1,2004,Saint Ralph (2004),Comedy Drama,Michael McGowan Jennifer Tilly Keir Gilchrist ...,0.998814
274,Spirited Away,Hayao Miyazaki,NaN,129,63.479,Studio Ghibli,8.5,2001,Spirited Away (Sen to Chihiro no kamikakushi) ...,Adventure Animation Fantasy,Hayao Miyazaki Bunta Sugawara Ken Yasuda Mari ...,0.998602
11802,The Evil in Us,Jason William Lee,Ren√©e St. Cyr,396004,7.024,Sandcastle Pictures,4.8,2016,The Evil in Us (2016),Horror,Jason William Lee Debs Howard Tatyana Forrest ...,0.998504
3424,Powder Blue,Timothy Linh Bui,Stephane Gauger,17740,9.142,Blue Snow Productions Eleven Eleven Films Spir...,6.0,2009,Powder Blue (2009),Drama,Timothy Linh Bui Jessica Biel Sala Baker Ray L...,0.998450
15189,The Book of Daniel,Anna Zielinski,Chuck Konzelman Cary Solomon,227859,63.295,Pure Flix Entertainment,7.1,2013,The Book of Daniel (2013),Fantasy,Anna Zielinski Lance Henriksen Alice Amter Rob...,0.998441
17238,The Last Season,Sara Dosa,NaN,285026,6.196,Filament Productions LLC Department of Motion ...,6.3,2014,"Last Season, The (2014)",Documentary,Sara Dosa Non Filament Productions LLC Depart...,0.998408
8413,Listening,Khalil Sullins None,Khalil Sullins,331592,7.390,Young Medium Listen Film,5.7,2014,Listening (2015),Sci-Fi,Khalil Sullins None Thomas Stroppel Christine ...,0.998397

In [9]:
get_recs(149, collaborative_embeddings, movies_with_tag)

,index,primaryTitle,Directors,Writers,tmdb_id,popularity,company_name,tmdb_avgRating,release_year_int,movieId,title,genres,document,similarity_score
149,149,The Lord of the Rings: The Return of the King,Peter Jackson None,J.R.R. Tolkien Fran Walsh Philippa Boyens,122,67.803,New Line Cinema WingNut Films The Saul Zaentz ...,8.5,2003,157,"Lord of the Rings: The Return of the King, The...",Action Adventure Drama Fantasy,Peter Jackson None Sean Bean Cate Blanchett Mi...,1.000000
1391,1391,People I Know,Daniel Algrant None,Jon Robin Baitz,11458,11.481,NaN,5.5,2002,6942,People I Know (2002),Crime Drama,Daniel Algrant None Al Pacino Kim Basinger T√©a...,0.486500
167,167,Hamlet,Michael Almereyda None,William Shakespeare,10688,11.871,Miramax double A Films,6.0,2000,735,Hamlet (2000),Crime Drama Romance Thriller,Michael Almereyda None Liev Schreiber Bill Mur...,0.469454
788,788,Dust,Milcho Manchevski None,Aneta Le≈°nikovska Milcho Manchevski,16405,5.526,British Screen Productions Alta Films S.A. Bri...,5.5,2001,10206,Dust (2001),Drama Western,Milcho Manchevski None Vera Farmiga Joseph Fie...,0.458999
1472,1472,The Nugget,Bill Bennett,NaN,6382,2.883,B.J. Films,6.0,2002,12343,"Nugget, The (2002)",Comedy,Bill Bennett Eric Bana Stephen Curry Max Culle...,0.428827
5483,5483,Dumplings,Fruit Chan None,Pik-Wah Lee Lilian Lee,9060,6.391,Applause Pictures,6.4,2004,671,Dumplings (Gaau ji) (2004),Drama Horror Thriller,Fruit Chan None Bai Ling Miriam Yeung Tony Leu...,0.425973
510,510,Looking for Alibrandi,Kate Woods,Melina Marchetta,25069,3.936,NaN,6.8,2000,10481,Looking for Alibrandi (2000),Drama,Kate Woods Greta Scacchi Anthony LaPaglia Leea...,0.408398
516,516,Agent Red,Jim Wynorski Damian Lee,Kevin Bernhardt Steve Latshaw David Riggs,51422,7.124,Phoenician Entertainment Captured Productions ...,4.7,2000,8050,Agent Red (2000),Action,Jim Wynorski Damian Lee Dolph Lundgren Stephen...,0.405068
7128,7128,Manda Bala (Send a Bullet),Jason Kohn,NaN,18181,6.727,NaN,6.0,2007,15445,Send a Bullet (Manda Bala) (2007),Documentary,Jason Kohn Non Manda Bala (Send a Bullet) is...,0.402869
324,324,Love & Basketball,Gina Prince-Bythewood,NaN,14736,9.958,40 Acres and a Mule Filmworks,7.6,2000,2482,Love and Basketball (2000),Drama Romance,Gina Prince-Bythewood Tyra Banks Boris Kodjoe ...,0.401720

In [32]:
get_recs(149, content_embeddings_with_tag_idx, movies_with_rating)

,primaryTitle,Directors,Writers,tmdb_id,company_name,movieId,genres,ratings_count,avg_rating,similarity_score
149,The Lord of the Rings: The Return of the King,Peter Jackson None,J.R.R. Tolkien Fran Walsh Philippa Boyens,122,New Line Cinema WingNut Films The Saul Zaentz ...,157,Action Adventure Drama Fantasy,57378,4.102853,1.000000
8590,All Good Things,Andrew Jarecki None,Marc Smerling Marcus Hinchey,46503,The Weinstein Company,3649,Drama Mystery Thriller,335,3.062687,0.962171
6064,The Chronicles of Narnia: Prince Caspian,Andrew Adamson None,C.S. Lewis Christopher Markus Stephen McFeely ...,2454,Walt Disney Pictures Walden Media Stillking Fi...,1412,Adventure Children Fantasy,3527,3.216898,0.947960
150,The Lord of the Rings: The Two Towers,Peter Jackson None,J.R.R. Tolkien Fran Walsh Stephen Sinclair Phi...,121,New Line Cinema WingNut Films The Saul Zaentz ...,116,Adventure Fantasy,56696,4.074705,0.944017
5750,Raising Jeffrey Dahmer,Rich Ambler,Wood Dickinson Christopher Ryan,40012,Renegade Pictures,15257,Drama Horror,4,1.125000,0.942271
8244,Blue Valentine,Derek Cianfrance None,Joey Curtis Cami Delavigne,46705,Cottage Industries Incentive Filmed Entertainm...,386,Drama Romance,1890,3.676190,0.942149
10234,Barney's Version,Richard J. Lewis,Mordecai Richler Michael Konyves,46829,Serendipity Point Films,1869,Drama,343,3.632653,0.934729
3587,Stealth,Rob Cohen,W.D. Richter Chad Glass,10048,Original Film Phoenix Pictures Laura Ziskin Pr...,1012,Action Adventure Sci-Fi Thriller,924,2.510281,0.926382
1916,8 Mile,Curtis Hanson,Scott Silver,65,Mikona Productions GmbH & Co. KG Imagine Enter...,648,Drama,7702,3.283433,0.925454
19897,Mystic Game,Artyom Aksenenko,Oleg Sirotkin,430343,Kinodanz,12410,Adventure Fantasy,2,4.250000,0.922533

In [17]:
get_recs(157, content_embeddings_with_movie_idx, movies_with_tag_movie_index)

,primaryTitle,Directors,Writers,tmdb_id,popularity,company_name,tmdb_avgRating,release_year_int,title,genres,document,similarity_score
157,The Lord of the Rings: The Return of the King,Peter Jackson None,J.R.R. Tolkien Fran Walsh Philippa Boyens,122,67.803,New Line Cinema WingNut Films The Saul Zaentz ...,8.5,2003,"Lord of the Rings: The Return of the King, The...",Action Adventure Drama Fantasy,Peter Jackson None Sean Bean Cate Blanchett Mi...,1.000000
592,Dunkirk,Christopher Nolan,Daniel Arkin,374720,40.669,Warner Bros. Pictures Syncopy,7.5,2017,Dunkirk (2017),Action Drama Thriller War,Christopher Nolan Tom Hardy Michael Caine Cill...,0.989053
81,The Lord of the Rings: The Fellowship of the Ring,Peter Jackson None,J.R.R. Tolkien Fran Walsh Philippa Boyens,120,77.541,New Line Cinema WingNut Films The Saul Zaentz ...,8.3,2001,"Lord of the Rings: The Fellowship of the Ring,...",Adventure Fantasy,Peter Jackson None Sean Bean Cate Blanchett El...,0.985835
116,The Lord of the Rings: The Two Towers,Peter Jackson None,J.R.R. Tolkien Fran Walsh Stephen Sinclair Phi...,121,67.340,New Line Cinema WingNut Films The Saul Zaentz ...,8.3,2002,"Lord of the Rings: The Two Towers, The (2002)",Adventure Fantasy,Peter Jackson None Sean Bean Cate Blanchett Mi...,0.984632
320,War Horse,Steven Spielberg,Michael Morpurgo Richard Curtis Lee Hall Nick ...,57212,22.889,Touchstone Pictures Amblin Entertainment Relia...,7.3,2011,War Horse (2011),Drama War,Steven Spielberg Tom Hiddleston Benedict Cumbe...,0.980997
15844,Blush,Wim Vandekeybus,Peter Verhelst,108639,1.883,Ultima Vez Sciapode CCCP Le Fresnoy,4.3,2005,Blush (2005),Drama Fantasy Romance,Wim Vandekeybus Elena Fokina Laura Aris Alvare...,0.977193
10689,Ghost Mountaineer,Urmas Eero Liiv,NaN,324183,1.401,Kopli Kinokompanii O√ú,5.3,2015,Ghost mountaineer (2015),(no genres listed),Urmas Eero Liiv Liis Lass Reimo Sagor Priit Pi...,0.975399
213,Jarhead,Sam Mendes,William Broyles Jr. Anthony Swofford Eric Ramsey,25,18.919,Red Wagon Entertainment Neal Street Production...,6.6,2005,Jarhead (2005),Action Drama War,Sam Mendes Jake Gyllenhaal Jamie Foxx Peter Sa...,0.974168
884,Last Days in Vietnam,Rory Kennedy,Mark Bailey Keven McAlester,250761,7.878,Moxie Firecracker Films,7.4,2014,Last Days in Vietnam (2014),Documentary War,Rory Kennedy Non Mark Bailey Keven McAlester M...,0.974131
9930,S21: The Khmer Rouge Killing Machine,Rithy Panh,NaN,43936,1.710,ARTE France Cin√©ma Ina,7.5,2003,"S21: The Khmer Rouge Death Machine (S-21, la m...",Documentary War,Rithy Panh Chum Mey Khieu 'Poev' Ches Yeay Che...,0.968721

In [21]:
get_recs(81, collaborative_embeddings_3, movies_with_tag_movie_index)

,primaryTitle,Directors,Writers,tmdb_id,popularity,company_name,tmdb_avgRating,release_year_int,title,genres,document,similarity_score
81,The Lord of the Rings: The Fellowship of the Ring,Peter Jackson None,J.R.R. Tolkien Fran Walsh Philippa Boyens,120,77.541,New Line Cinema WingNut Films The Saul Zaentz ...,8.3,2001,"Lord of the Rings: The Fellowship of the Ring,...",Adventure Fantasy,Peter Jackson None Sean Bean Cate Blanchett El...,1.000000
350,Whiplash,Damien Chazelle None,Jasmine McGlade,244786,37.388,Bold Films Blumhouse Productions Right of Way ...,8.4,2014,Whiplash (2014),Drama,Damien Chazelle None Melissa Benoist J.K. Simm...,0.781307
880,Song of the Sea,Tomm Moore,Will Collins Adrien Merigeau,110416,12.600,Digital Graphics Big Farm Cartoon Saloon Super...,8.0,2014,Song of the Sea (2014),Animation Children Fantasy,Tomm Moore Fionnula Flanagan Brendan Gleeson J...,0.756870
354,Wild Tales,Dami√°n Szifron,Germ√°n Servidio,265195,16.181,Warner Bros. Pictures El Deseo K & S Films Tel...,7.9,2014,Wild Tales (2014),Comedy Drama Thriller,Dami√°n Szifron Leonardo Sbaraglia Ricardo Dar√≠...,0.752979
2175,Black Book,Paul Verhoeven None,Gerard Soeteman,9075,10.007,Studio Babelsberg Motel Films Motion Investmen...,7.5,2006,Black Book (Zwartboek) (2006),Drama Thriller War,Paul Verhoeven None Carice van Houten Matthias...,0.742859
371,The Lives of Others,Florian Henckel von Donnersmarck None,Hagen Keller,582,11.281,Creado Film Wiedemann & Berg Film ARD,8.1,2006,"Lives of Others, The (Das leben der Anderen) (...",Drama Romance Thriller,Florian Henckel von Donnersmarck None Herbert ...,0.736716
160,Eternal Sunshine of the Spotless Mind,Michel Gondry,Charlie Kaufman Pierre Bismuth,38,33.859,Focus Features Anonymous Content This Is That ...,8.1,2004,Eternal Sunshine of the Spotless Mind (2004),Drama Romance Sci-Fi,Michel Gondry Kirsten Dunst Elijah Wood Mark R...,0.732362
123,City of God,Fernando Meirelles K√°tia Lund,Paulo Lins Br√°ulio Mantovani,598,24.671,O2 Filmes Videofilmes Wild Bunch Hank Levine F...,8.4,2002,City of God (Cidade de Deus) (2002),Action Adventure Crime Drama Thriller,Fernando Meirelles K√°tia Lund Alice Braga Graz...,0.728234
358,Spotlight,Tom McCarthy,Josh Singer,314365,17.367,Participant Media Anonymous Content Rocklin / ...,7.8,2015,Spotlight (2015),Thriller,Tom McCarthy Michael Keaton Rachel McAdams Mar...,0.727433
297,The Secret in Their Eyes,Juan Jos√© Campanella,Eduardo Sacheri A√≠da Bortnik,25376,14.862,Canal+ Espa√±a 100 Bares Tornasol Films Ministe...,8.0,2009,"Secret in Their Eyes, The (El secreto de sus o...",Crime Drama Mystery Romance Thriller,Juan Jos√© Campanella Pablo Rago Ricardo Dar√≠n ...,0.724402

In [28]:
get_recs(81, collaborative_embeddings_3, movies_with_movie_index_rating)

,movieId,primaryTitle,Directors,tmdb_id,company_name,genres,ratings_count,avg_rating,similarity_score
81,81,The Lord of the Rings: The Fellowship of the Ring,Peter Jackson None,120,New Line Cinema WingNut Films The Saul Zaentz ...,Adventure Fantasy,61883,4.097943,1.000000
350,350,Whiplash,Damien Chazelle None,244786,Bold Films Blumhouse Productions Right of Way ...,Drama,10907,4.127808,0.781307
880,880,Song of the Sea,Tomm Moore,110416,Digital Graphics Big Farm Cartoon Saloon Super...,Animation Children Fantasy,1077,3.979573,0.756870
354,354,Wild Tales,Dami√°n Szifron,265195,Warner Bros. Pictures El Deseo K & S Films Tel...,Comedy Drama Thriller,1881,4.097023,0.752979
2175,2175,Black Book,Paul Verhoeven None,9075,Studio Babelsberg Motel Films Motion Investmen...,Drama Thriller War,1097,3.786235,0.742859
371,371,The Lives of Others,Florian Henckel von Donnersmarck None,582,Creado Film Wiedemann & Berg Film ARD,Drama Romance Thriller,9670,4.199845,0.736716
160,160,Eternal Sunshine of the Spotless Mind,Michel Gondry,38,Focus Features Anonymous Content This Is That ...,Drama Romance Sci-Fi,35064,4.073480,0.732362
123,123,City of God,Fernando Meirelles K√°tia Lund,598,O2 Filmes Videofilmes Wild Bunch Hank Levine F...,Action Adventure Crime Drama Thriller,21558,4.184897,0.728234
358,358,Spotlight,Tom McCarthy,314365,Participant Media Anonymous Content Rocklin / ...,Thriller,5211,4.079351,0.727433
297,297,The Secret in Their Eyes,Juan Jos√© Campanella,25376,Canal+ Espa√±a 100 Bares Tornasol Films Ministe...,Crime Drama Mystery Romance Thriller,2390,4.006485,0.724402

In [30]:
get_recs(477, collaborative_embeddings_3, movies_with_movie_index_rating)

,movieId,primaryTitle,Directors,tmdb_id,company_name,genres,ratings_count,avg_rating,similarity_score
477,477,Avengers: Infinity War,Joe Russo Anthony Russo,299536,Marvel Studios,Action Adventure Sci-Fi,2668,3.956709,1.000000
1073,1073,The Visitor,Tom McCarthy,12473,Overture Films,Drama Romance,1142,3.828809,0.800531
309,309,Elite Squad 2: The Enemy Within,Jos√© Padilha None,47931,Feij√£o Filmes Riofilme Zazen Produ√ß√µes Globo F...,Action Crime Drama,1673,3.994620,0.792874
1536,1536,In the Mood for Love,Kar-Wai Wong None,843,Block 2 Pictures Jet Tone Production Orly Film...,Drama Romance,2997,4.030364,0.783287
868,868,Frances Ha,Noah Baumbach,121986,Scott Rudin Productions RT Features Pine Distr...,Comedy Drama,880,3.742614,0.779819
2567,2567,Mysterious Skin,Gregg Araki None,11171,Desperate Pictures Fortissimo Films Antidote F...,Drama Mystery,1388,3.801873,0.769900
2178,2178,Away from Her,Sarah Polley None,1919,Lionsgate,Drama,559,3.726297,0.768269
2439,2439,The Wind Rises,Hayao Miyazaki None,149870,"Studio Ghibli Toho Pictures, Inc. Touchstone P...",Animation Drama Romance,1109,3.926510,0.763682
2175,2175,Black Book,Paul Verhoeven None,9075,Studio Babelsberg Motel Films Motion Investmen...,Drama Thriller War,1097,3.786235,0.762191
1543,1543,The Skin I Live In,Pedro Almod√≥var None,63311,El Deseo Canal+ Espa√±a ICAA Instituto de Cr√©di...,Drama,1480,3.743581,0.761373

In [19]:
get_recs(1847, content_embeddings_with_movie_idx, movies_with_tag_movie_index)

,primaryTitle,Directors,Writers,tmdb_id,popularity,company_name,tmdb_avgRating,release_year_int,title,genres,document,similarity_score
1847,3 Idiots,Rajkumar Hirani None,Vidhu Vinod Chopra Abhijat Joshi Chetan Bhagat...,20453,18.011,Vidhu Vinod Chopra Productions Vinod Chopra Films,8.0,2009,3 Idiots (2009),Comedy Drama Romance,Rajkumar Hirani None Boman Irani Ali Fazal Mon...,1.000000
5474,The Legend Is Born: Ip Man,Herman Yau,Erica Li Sean Whitley,44249,3.093,Mei Ah Entertainment,6.8,2010,The Legend Is Born: Ip Man (2010),Action Drama,Herman Yau Sammo Hung Yuen Biao Xu Jiao Erica ...,0.977094
16071,Adventure Club,Geoff Anderson,Fred Ewanuick,437331,6.324,Trilight Entertainment Montague Entertainment,6.5,2017,The Adventure Club (2017),Children,Geoff Anderson Billy Zane Kim Coates Dalila Be...,0.970271
11841,Rampage: Capital Punishment,Uwe Boll,NaN,250388,12.515,Amok II Productions Boll Kino Beteiligungs Gmb...,5.8,2014,Rampage: Capital Punishment (2014),Action Crime Thriller,Uwe Boll Matt Frewer Lochlyn Munro Brendan Fle...,0.968861
6612,How I Killed My Father,Anne Fontaine,Jacques Fieschi,60608,4.099,NaN,6.5,2001,How I Killed My Father (a.k.a. My Father and I...,Drama,Anne Fontaine Amira Casar Fran√ßois Berl√©and Ch...,0.967799
7146,Bienvenue √† bord,Eric Lavaine,H√©ctor Cabello Reyes,75198,10.093,Same Player Path√©! Appaloosa Films M6 Films,5.5,2011,Bienvenue √† bord (2011),Comedy,Eric Lavaine Luisa Ranieri G√©rard Darmon Franc...,0.966617
4794,In the Electric Mist,Bertrand Tavernier,James Lee Burke Jerzy Kromolowski Mary Olson-K...,13975,13.253,Little Bear Ithaca Pictures,6.1,2009,In the Electric Mist (2009),Drama Mystery,Bertrand Tavernier John Goodman Peter Sarsgaar...,0.960469
20741,Michou d'Auber,Thomas Gilou,Jean Cosmos Messaoud Hattau,14650,4.225,MP Productions TF1 Films Production EuropaCorp,6.3,2007,Michou d'Auber (2007),Drama Thriller,Thomas Gilou G√©rard Depardieu Mathieu Amalric ...,0.958477
3827,Highwaymen,Robert Harmon,Craig Mitchell Hans Bauer,29979,12.728,New Line Cinema Cornice Entertainment Millenni...,5.7,2004,Highwaymen (2003),Action Crime Thriller,Robert Harmon Rhona Mitra Frankie Faison Colm ...,0.956794
9052,With Great Power: The Stan Lee Story,Terry Dougas Will Hess Nikki Frakes,NaN,86843,8.545,1821 Pictures Emerging Entertainment,6.6,2010,With Great Power: The Stan Lee Story (2012),Documentary,Terry Dougas Will Hess Nikki Frakes Kirsten Du...,0.955518

In [21]:
get_recs(8690, content_embeddings_with_tag_idx, movies_with_tag)

,index,primaryTitle,Directors,Writers,tmdb_id,popularity,company_name,tmdb_avgRating,release_year_int,movieId,title,genres,document,similarity_score
8690,8690,3 Idiots,Rajkumar Hirani None,Vidhu Vinod Chopra Abhijat Joshi Chetan Bhagat...,20453,18.011,Vidhu Vinod Chopra Productions Vinod Chopra Films,8.0,2009,1847,3 Idiots (2009),Comedy Drama Romance,Rajkumar Hirani None Boman Irani Ali Fazal Mon...,1.000000
19921,19921,Ho Mann Jahaan,Asim Raza None,Yasir Hussain Imtisal Abbasi Rashna Abdi Afzal...,384547,1.751,The Vision Factory Films,6.1,2015,21466,Ho Mann Jahaan (2016),Drama,Asim Raza None Adeel Husain Fawad Khan Hamza A...,0.976608
9631,9631,We Can Do That,Giulio Manfredonia None,Fabio Bonifacci,23619,4.138,Rizzoli Film,7.3,2008,13913,We Can Do That (2008),Comedy,Giulio Manfredonia None Rosa Pianeta Pietro Ra...,0.976364
16753,16753,"Pulp: A Film About Life, Death & Supermarkets",Florian Habicht,Peter O'Donoghue,253332,7.628,Oscilloscope Pistachio Pictures,7.2,2014,17071,"Pulp: a Film About Life, Death & Supermarkets ...",Documentary,Florian Habicht Jarvis Cocker Richard Hawley P...,0.976059
5740,5740,Bandage,Takeshi Kobayashi,Shunji Iwai Chika Kan,74495,1.670,Nippon Television Network Corporation D.N. Dre...,6.4,2010,17306,Bandage (2010),Drama Romance,Takeshi Kobayashi Ayumi Ito Nobuaki Kaneko Jin...,0.975918
13019,13019,Talihina Sky: The Story of Kings of Leon,Stephen C. Mitchell,NaN,73350,7.570,Phear Creative,5.8,2011,14632,Talihina Sky: The Story of Kings of Leon (2011),Documentary,Stephen C. Mitchell Jared Followill Caleb Foll...,0.974588
11897,11897,Attenberg,Athina Rachel Tsangari None,NaN,62321,4.421,MEDIA Programme of the European Union Haos Fil...,6.1,2010,7956,Attenberg (2010),Drama,Athina Rachel Tsangari None Ariane Labed Yorgo...,0.972757
20791,20791,Aanandam,Ganesh Raj None,Ganesh Raj,422603,2.650,Cast N' Crew Habit of Life,6.9,2016,8217,Aanandam (2016),Adventure Comedy Romance,Ganesh Raj None Arun Kurian Anarkali Marikar S...,0.972699
4588,4588,G@me,Satoshi Isaka,Masaya Ozaki Keigo Higashino Hiroyoshi Koiwai,61492,1.734,"Toho Company, Ltd. Fuji Television Network DEN...",6.0,2003,18863,G@me (2003),Thriller,Satoshi Isaka Ryo Ishibashi Yukie Nakama Ry√ªd√¥...,0.972689
10548,10548,Mighty Uke,Tony Coleman,NaN,173938,1.150,Tiny Goat Films Sphinx Productions,0.0,2010,10647,Mighty Uke (2010),Documentary,Tony Coleman Non Tiny Goat Films Sphinx Produ...,0.971218

In [33]:
get_recs(18480, content_embeddings_with_tag_idx, movies_with_rating)

,primaryTitle,Directors,Writers,tmdb_id,company_name,movieId,genres,ratings_count,avg_rating,similarity_score
18480,Avengers: Infinity War,Joe Russo Anthony Russo,Jack Kirby Stan Lee Christopher Markus Stephen...,299536,Marvel Studios,477,Action Adventure Sci-Fi,2668,3.956709,1.000000
13519,Guardians of the Galaxy,James Gunn,Bill Mantlo Keith Giffen Nicole Perlman Dan Ab...,118340,Marvel Studios,351,Action Adventure Sci-Fi,15574,3.932580,0.989677
12979,The Amazing Spider-Man 2,Marc Webb,Stan Lee James Vanderbilt Alex Kurtzman Robert...,102382,Marvel Entertainment Columbia Pictures Avi Ara...,1488,Action Sci-Fi IMAX,2585,3.112379,0.984785
5665,Ant-Man,Peyton Reed None,Stan Lee Larry Lieber Edgar Wright Joe Cornish...,102899,Marvel Studios,802,Action Adventure Sci-Fi,5806,3.590424,0.983780
6787,The Avengers,Joss Whedon None,Zak Penn Stan Lee Joss Whedon Jack Kirby Bryan...,24428,Marvel Studios Paramount,318,Action Adventure Sci-Fi IMAX,17700,3.799011,0.976166
3297,Batman Begins,Christopher Nolan None,Bob Kane David S. Goyer Paul Dini Martin Asbury,272,Warner Bros. Pictures DC Comics DC Entertainme...,205,Action Crime IMAX,32027,3.934430,0.974744
5406,The Dark Knight,Christopher Nolan None,Bob Kane David S. Goyer Jonathan Nolan Bill Fi...,155,DC Comics Legendary Pictures Syncopy Isobel Gr...,288,Action Crime Drama IMAX,44741,4.173756,0.971238
5176,Captain America: The First Avenger,Joe Johnston None,Jack Kirby Joe Simon Christopher Markus Stephe...,1771,Marvel Studios Paramount Marvel Entertainment,1136,Action Adventure Sci-Fi Thriller War,8492,3.521785,0.964574
5160,Pan's Labyrinth,Guillermo del Toro None,Ra√∫l Monge,1417,Estudios Picasso Esperanto Filmoj Tequila Gang...,251,Drama Fantasy Thriller,20509,3.982544,0.962110
7673,500 Days of Summer,Marc Webb,Scott Neustadter Michael H. Weber,19913,Fox Searchlight Pictures Watermark Pictures Du...,425,Comedy Drama Romance,12437,3.754684,0.960436

In [34]:
get_recs(5406, content_embeddings_with_tag_idx, movies_with_rating)

,primaryTitle,Directors,Writers,tmdb_id,company_name,movieId,genres,ratings_count,avg_rating,similarity_score
5406,The Dark Knight,Christopher Nolan None,Bob Kane David S. Goyer Jonathan Nolan Bill Fi...,155,DC Comics Legendary Pictures Syncopy Isobel Gr...,288,Action Crime Drama IMAX,44741,4.173756,1.000000
5665,Ant-Man,Peyton Reed None,Stan Lee Larry Lieber Edgar Wright Joe Cornish...,102899,Marvel Studios,802,Action Adventure Sci-Fi,5806,3.590424,0.980979
12979,The Amazing Spider-Man 2,Marc Webb,Stan Lee James Vanderbilt Alex Kurtzman Robert...,102382,Marvel Entertainment Columbia Pictures Avi Ara...,1488,Action Sci-Fi IMAX,2585,3.112379,0.980946
5160,Pan's Labyrinth,Guillermo del Toro None,Ra√∫l Monge,1417,Estudios Picasso Esperanto Filmoj Tequila Gang...,251,Drama Fantasy Thriller,20509,3.982544,0.979078
12813,Captain America: The Winter Soldier,Joe Russo Anthony Russo,Jack Kirby Joe Simon Christopher Markus Stephe...,100402,Marvel Studios,790,Action Adventure Sci-Fi IMAX,8279,3.709023,0.972683
18480,Avengers: Infinity War,Joe Russo Anthony Russo,Jack Kirby Stan Lee Christopher Markus Stephen...,299536,Marvel Studios,477,Action Adventure Sci-Fi,2668,3.956709,0.971238
7673,500 Days of Summer,Marc Webb,Scott Neustadter Michael H. Weber,19913,Fox Searchlight Pictures Watermark Pictures Du...,425,Comedy Drama Romance,12437,3.754684,0.966153
5176,Captain America: The First Avenger,Joe Johnston None,Jack Kirby Joe Simon Christopher Markus Stephe...,1771,Marvel Studios Paramount Marvel Entertainment,1136,Action Adventure Sci-Fi Thriller War,8492,3.521785,0.965486
2265,Spider-Man 2,Sam Raimi,Stan Lee Steve Ditko Alfred Gough Miles Millar...,558,Marvel Enterprises Sony Pictures Columbia Pict...,174,Action Adventure Sci-Fi IMAX,21989,3.453454,0.964525
19705,Get Out,Jordan Peele,NaN,419430,Monkeypaw Productions Blumhouse Productions QC...,901,Horror,3871,3.951563,0.961785

In [27]:
get_recs(1136, content_embeddings_with_movie_idx, movies_with_tag_movie_index)

,primaryTitle,Directors,Writers,tmdb_id,popularity,company_name,tmdb_avgRating,release_year_int,title,genres,document,similarity_score
1136,Captain America: The First Avenger,Joe Johnston None,Jack Kirby Joe Simon Christopher Markus Stephe...,1771,69.605,Marvel Studios Paramount Marvel Entertainment,6.9,2011,Captain America: The First Avenger (2011),Action Adventure Sci-Fi Thriller War,Joe Johnston None Sebastian Stan Samuel L. Jac...,1.000000
740,Captain America: Civil War,Joe Russo Anthony Russo,Jack Kirby Joe Simon Christopher Markus Stephe...,271110,112.772,Marvel Studios,7.4,2016,Captain America: Civil War (2016),Action Sci-Fi Thriller,Joe Russo Anthony Russo Scarlett Johansson Rob...,0.990827
3925,Captain Marvel,Ryan Fleck Anna Boden None,Meg LeFauve Nicole Perlman Geneva Robertson-Dw...,299537,188.994,Marvel Studios,7.0,2019,Captain Marvel (2018),Action Adventure Sci-Fi,Ryan Fleck Anna Boden None Scarlett Johansson ...,0.978966
772,Thor,Kenneth Branagh,J. Michael Straczynski Mark Protosevich Ashley...,10195,70.924,Marvel Studios Paramount Marvel Entertainment,6.8,2011,Thor (2011),Action Adventure Drama Fantasy IMAX,Kenneth Branagh Anthony Hopkins Natalie Portma...,0.974206
600,The Punisher,Jonathan Hensleigh,Michael France Jonathan Hensleigh Stan Lee Ger...,7220,22.898,Lions Gate Films VIP Medienfonds 3 Valhalla Mo...,6.2,2004,"Punisher, The (2004)",Action Crime Thriller,Jonathan Hensleigh John Travolta Roy Scheider ...,0.970013
226,300,Zack Snyder None,Frank Miller Kurt Johnstad Michael B. Gordon L...,1271,39.081,Virtual Studios Legendary Pictures Hollywood G...,7.1,2006,300 (2007),Action Fantasy War IMAX,Zack Snyder None Lena Headey Gerard Butler Mic...,0.969145
131,X2: X-Men United,Bryan Singer,David Hayter Zak Penn Dan Harris Michael Dough...,36658,1.449,Marvel Enterprises The Donners' Company Bad Ha...,7.0,2003,X2: X-Men United (2003),Action Adventure Sci-Fi Thriller,Bryan Singer Hugh Jackman James Marsden Famke ...,0.968539
10943,Comic-Con Episode IV: A Fan's Hope,Morgan Spurlock,Joss Whedon Jeremy Chilnick Stan Lee,91356,7.458,Mutant Enemy Productions,6.8,2011,Comic-Con Episode IV: A Fan's Hope (2011),Documentary,Morgan Spurlock Seth Rogen Stan Lee Thomas Jan...,0.966999
7018,Two Men in Town,Rachid Bouchareb,Jos√© Giovanni Daniel Boulanger Olivier Lorelle...,254772,4.981,Tessalit Productions,5.6,2014,Two Men in Town (2014),Crime Drama,Rachid Bouchareb Harvey Keitel Reg E. Cathey B...,0.965294
21099,Mike Boy,Hamzah Tarzan,Hamzah Tarzan,469031,0.603,NaN,0.0,2017,Mike Boy (2017),Crime Mystery Thriller,Hamzah Tarzan Gerard Sanders Ron Gilbert Rober...,0.964629

In [28]:
get_recs(5176, content_embeddings_with_tag_idx, movies_with_tag)

,index,primaryTitle,Directors,Writers,tmdb_id,popularity,company_name,tmdb_avgRating,release_year_int,movieId,title,genres,document,similarity_score
5176,5176,Captain America: The First Avenger,Joe Johnston None,Jack Kirby Joe Simon Christopher Markus Stephe...,1771,69.605,Marvel Studios Paramount Marvel Entertainment,6.9,2011,1136,Captain America: The First Avenger (2011),Action Adventure Sci-Fi Thriller War,Joe Johnston None Sebastian Stan Samuel L. Jac...,1.000000
1755,1755,X2: X-Men United,Bryan Singer,David Hayter Zak Penn Dan Harris Michael Dough...,36658,1.449,Marvel Enterprises The Donners' Company Bad Ha...,7.0,2003,131,X2: X-Men United (2003),Action Adventure Sci-Fi Thriller,Bryan Singer Hugh Jackman James Marsden Famke ...,0.979707
27,27,X-Men,Bryan Singer,David Hayter Tom DeSanto Stan Lee John Coven L...,36657,1.774,Marvel Enterprises The Donners' Company Bad Ha...,7.0,2000,21,X-Men (2000),Action Adventure Sci-Fi,Bryan Singer Hugh Jackman James Marsden Famke ...,0.979428
2265,2265,Spider-Man 2,Sam Raimi,Stan Lee Steve Ditko Alfred Gough Miles Millar...,558,27.158,Marvel Enterprises Sony Pictures Columbia Pict...,7.1,2004,174,Spider-Man 2 (2004),Action Adventure Sci-Fi IMAX,Sam Raimi Kirsten Dunst Willem Dafoe Elizabeth...,0.977143
18479,18479,Captain Marvel,Ryan Fleck Anna Boden None,Meg LeFauve Nicole Perlman Geneva Robertson-Dw...,299537,188.994,Marvel Studios,7.0,2019,3925,Captain Marvel (2018),Action Adventure Sci-Fi,Ryan Fleck Anna Boden None Scarlett Johansson ...,0.976234
12813,12813,Captain America: The Winter Soldier,Joe Russo Anthony Russo,Jack Kirby Joe Simon Christopher Markus Stephe...,100402,59.956,Marvel Studios,7.7,2014,790,Captain America: The Winter Soldier (2014),Action Adventure Sci-Fi IMAX,Joe Russo Anthony Russo Scarlett Johansson Seb...,0.971911
5160,5160,Pan's Labyrinth,Guillermo del Toro None,Ra√∫l Monge,1417,29.471,Estudios Picasso Esperanto Filmoj Tequila Gang...,7.7,2006,251,"Pan's Labyrinth (Laberinto del fauno, El) (2006)",Drama Fantasy Thriller,Guillermo del Toro None Ivana Baquero Ariadna ...,0.969014
4152,4152,Spider-Man 3,Sam Raimi None,Alvin Sargent Stan Lee Steve Ditko Ivan Raimi,559,60.676,Columbia Pictures Laura Ziskin Productions Son...,6.2,2007,1046,Spider-Man 3 (2007),Action Adventure Sci-Fi Thriller IMAX,Sam Raimi None Kirsten Dunst Willem Dafoe Eliz...,0.967170
9297,9297,X-Men: First Class,Matthew Vaughn None,Bryan Singer Ashley Miller Zack Stentz Jane Go...,49538,1.801,Marvel Entertainment 20th Century Fox Dune Ent...,7.3,2011,774,X-Men: First Class (2011),Action Adventure Sci-Fi Thriller War,Matthew Vaughn None Jennifer Lawrence Hugh Jac...,0.965707
5406,5406,The Dark Knight,Christopher Nolan None,Bob Kane David S. Goyer Jonathan Nolan Bill Fi...,155,75.827,DC Comics Legendary Pictures Syncopy Isobel Gr...,8.5,2008,288,"Dark Knight, The (2008)",Action Crime Drama IMAX,Christopher Nolan None Christian Bale Morgan F...,0.965486